all_characters_unedited = ['abhimanyu','acharya','achyuta','adhiratha','agastya','agnihotra','airavata','ajatashatru','akshayapatra','alambasa','amrita','anga','arani','artha (wealth)','arundhati','ashtavakra','asita','asmaka','astra','aswamedhayajna','aswatthama','bahlika, dasharna,','bakasura','baladeva','balarama','balarama','bhagadatta','bhagawan','bharadwaja','bharata','bhima','bhishma','bhishmaka','bhojas','bhuminjaya','bibhatsu','brahma','brahmacharin','brahmacharya','brahmastra','brihadashwa','brihadratha','brihadyumna','brihannala','brihatbala','burisrwas','chala','chandala','charachitra','chavadi','chekitana','chitra','chitraksha','chitrangada','chitrasena','chitrasena','chitravarma','chitrayudha','darshana','daruka','dasharatha','devadatta','devaki','devata','devayani','devendra','dhananjaya','dhanusaksha','dharma','dharmagranthi','dharmananda','dharmaputra','dharmavyadha','dhartarashtras','dhaumya','dhrishtadyumna','dhrishtaketu','dhritarashtra','draupadi','drona','drupada','durdhara','durjaya','durmarsha','durmata','durmukha','durvasa','durvishaha','dushkarma','dussaha','dussasana','dwaitayana','ganapati','gandhari','gandharvas','gandiva','gangadwara','ghatotkacha','govinda','guru','halayudha','hamsa, hidimbaka, kamsa','hanuman','hastinapura','hrishikesha','ilvala','indrajit','indrakila','indrasena','iravan','jalasura','janaka','janamejaya','janardana','jarasandha','jarita, laputa','jaya','jayadratha','jayatsena','jayatsena','jnana','kacha','kagola','kambojas','kamsa','kanika','kanka','karna','kartavirya','kartikeya','kausikam','kekaya','keshava','ketama','khandavaprastha','kichaka','krauncha','krauncha-vyuha','kripacharya','krishna-dwaipayana','kritavarma','kshatradharma','kuchasthala','kumbhakarna','kundinapura','kunti','kunti-madri','kurma','lakshmana','lomasa','lopamudra','lordnarayana','madhava','madhusudana','mahavishnu','mahendra','maitreya','manasarovar','mandavya','mantra','maricha','markandeya','marutta','matali','medhavi','meru','nahusha','nakula','nala','nandini','nara','narada','narayana','narayanas','narayanasrama','nishada','nishadha','palasha','panchajanya','panchali','panchalya','pandu','parashara','paravasu','parikshit','partha','parvati','paurava','phalguna','pitamaha','prabhasa','pradyumna','pratikhami','pritha','ptirushottama','pundarikaksha','purochana','purumitra','radheya','raibhya','rajasuya','ravana','rishabha','rishyasringa','romapada','rudra','rudradance','rukma','sachidevi','sahadeva','saibya','saindhava','sairandhri','salva','salya','samba','samsaptaka','samvarta','sanga','sanjaya','sankulayuddha','santanu','sanyasin','sarasana','sarmishtha','satanika','satyajit','satyaki','satyavati','satyavrata','saugandhika','savyasachin','shakuni','shanta','shishupala','shveta','sikhandin','simhanada','sini','somadutta','srirama','srinjayas','srutayu, astutayu','srutayudha','subahu','subhadra','sudakshina','sudarshana','sudarshana','sudeshna','sugriva','sujata','suka','sumitra','supratika','susarma','suvarna','swarga','tantripala','uddalaka','umadevi','unchhavritti','upachitra','upaplavya','urvashi','valala','vali','vandi','varanavata','vashishtha','vasudeva','vasudhana','vedavyasa','vichitravirya','vikarna','vinda','anuvinda','virata','vishoka','visvarupa','viswarupa','vivimsati','vriddhakshatra','vrika','vrikodara','vrisha','achala','vrishasena','vrishnis, kekayas','vritra','vyasa','vyuha','yajna','yaksha','yama','yavakrida','yayati','yudhamanyu','yuyudhana','vaisampayana', 'yuyutsu','duryodhana', 'bhimasena']


all_characters = ['krishna',  'yudhishthira', 'bhima', 'arjuna', 'nakula', 'sahadeva', 'bhishma', 'siva', 'parvati', 'vyasa', 'balarama', 'devaki', 'dhrishtadyumna', 'abhimanyu', 'daruka', 'adhiratha', 'agastya', 'arundhati', 'ashtavakra', 'aswatthama', 'asita', 'bharadwaja', 'brahma', 'brihadaswa', 'brihadratha', 'brihadyumna', 'chitrangada', 'dasaratha', 'dhanusaksha', 'dhaumya', 'dhrishtaketu', 'drupada', 'durvasa', 'ganapati', 'gandhari', 'ghalotkacha', 'hanuman',  'indrasena', 'iravan', 'janaka', 'janamejaya', 'jayatsena', 'kagola', 'kanika', 'kausikam', 'kartikeya', 'kekaya', 'ketama', 'kichaka', 'kripacharya', 'kritavarma', 'kunti', 'durvasa', 'madri', 'lakshmana', 'lomasa', 'lopamudra', 'mahendra', 'maitreya', 'mandavya', 'maricha', 'markandeya', 'marutta', 'kausika', 'brihaspati', 'matali', 'nahusha', 'nala', 'nandini', 'narada', 'pandu', 'parasara', 'paravasu', 'rukmini', 'prabhasa', 'pradyumna', 'pritha', 'purochana', 'purumitra', 'raibhya', 'sanatkumar', 'aditi', 'radheya', 'radha', 'romapada', 'rukma', 'sachidevi', 'saibya', 'samba', 'sanga', 'shanta', 'santanu', 'satyajit', 'satyaki', 'satyavati', 'sikhandin', 'somadutta', 'subahu', 'subhadra', 'sudeshna', 'sugriva', 'sujata', 'suka', 'supratika', 'susarma', 'sveta', 'uddalaka', 'unchhavritti', 'urvasi', 'yayati', 'mandhata', 'vali', 'vasishtha', 'ganga', 'vikarna', 'vedavyasa', 'vichitravirya', 'vikarna', 'visoka', 'visvarupa', 'vritra', 'twashta', 'yama', 'yavakrida', 'yayati', 'sarmishtha', 'sukracharya', 'yudhamanyu', 'yuyudhana', 'yuyutsu', 'dhritarashtra', 'drona', 'anga', 'asmaka', 'bhagadatta', 'brihatbala', 'bhuminjaya', 'burisrwas', 'bibhatsu', 'chala', 'charachitra', 'chekitana', 'chitraksha', 'chitra', 'chitrayudha', 'devayani', 'chitravarma', 'chitrasena', 'durdhara', 'durjaya', 'durmarsha', 'durmata', 'durmukha', 'durvishaha', 'dushkarma', 'dussaha', 'jarasandha', 'jaya', 'jayadratha', 'karna', 'kartavirya', 'paurava', 'sakuni', 'salva', 'sisupala', 'sarasana', 'sarmishtha', 'satanika', 'satyavrata', 'sudakshina', 'sudarsana', 'suvarna', 'srutayu', 'astutayu', 'srutayudha', 'upachitra', 'vasudhana', 'vinda', 'anuvinda', 'vivimsati', 'vriddhakshatra', 'vrika', 'vrisha', 'achala', 'vrishnis', 'kekayas', 'vrishasena', 'vaisampayana','alambasa', 'bakasura', 'hamsa', 'hidimbaka', 'kamsa', 'ilvala', 'indrajit', 'jalasura', 'kumbhakarna', 'ravana', 'duryodhana', 'krishnas']

important_characters = ['abhimanyu', 'aditi', 'agastya', 'alambasa', 'arjuna', 'arundhati', 'asita', 'aswatthama', 'bakasura', 'balarama', 'bharadwaja', 'bhima', 'bhishma', 'bhuminjaya', 'bibhatsu', 'brahma', 'brihadaswa', 'brihaspati', 'chekitana', 'chitrangada', 'devaki', 'dhrishtadyumna', 'dhrishtaketu', 'dhritarashtra', 'drona', 'drupada', 'durjaya', 'durvasa', 'durvasa', 'duryodhana','ganapati', 'gandhari', 'ganga', 'ghalotkacha', 'hamsa', 'hidimbaka',  'indrajit', 'jalasura', 'janamejaya', 'jarasandha', 'jayadratha', 'kamsa', 'karna', 'kartavirya', 'kekayas', 'kichaka', 'kripacharya', 'krishna', 'kritavarma', 'kunti', 'lomasa', 'lopamudra', 'madri', 'maitreya', 'mandavya', 'maricha', 'markandeya', 'matali', 'nahusha', 'nakula', 'nala', 'narada', 'pandu', 'parasara', 'parvati', 'pradyumna', 'purochana', 'romapada', 'rukma', 'rukmini', 'sachidevi', 'sahadeva', 'sakuni', 'salva', 'samba', 'santanu', 'satyajit', 'satyaki', 'satyavati', 'satyavrata', 'sikhandin', 'sisupala', 'siva', 'somadutta', 'subahu', 'subhadra', 'sudakshina', 'sudarsana', 'sudeshna', 'suka', 'sukracharya', 'urvasi', 'vasishtha', 'vedavyasa', 'vichitravirya', 'vaisampayana','vikarna', 'vikarna', 'vrishasena', 'vrishnis', 'vyasa', 'yama', 'yayati', 'yudhishthira' ]

very_important_characters = ['krishna', 'arjuna', 'bhima', 'yudhishthira', 'abhimanyu', 'bhishma', 'dhritarashtra', 'nakula', 'sahadeva', 'duryodhana']

# important_characters = ['krishna', 'achuta', 'achyuta', 'bhagawan', 'govinda', 'hrishikesha', 'janardana', 'kesava', 'kurma', 'narayana', 'madhava', 'madhusudana', 'mahavishnu', 'vishnu', 'pundarikaksha', 'ptirushottama', 'purushottama', 'vasudeva', 'viswarupa', 'yudhishthira', 'ajatasatru', 'dharmananda', 'kanka', 'bhima', 'valala', 'vrikodara', 'arjuna', 'brihannola', 'dhananjaya', 'nara', 'partha', 'phalguna', 'savyasachin', 'nakula', 'dharmagranthi', 'sahadeva', 'tantripala', 'bhishma', 'devavrata', 'siva', 'rudra', 'parvati', 'umadevi', 'krishna-dwaipayana', 'vyasa', 'vedavyasa', 'balarama', 'halayudha', 'devaki', 'dhrishtadyumna', 'abhimanyu', 'bharata', 'daruka', 'adhiratha', 'agastya', 'arundhati', 'ashtavakra', 'aswathama', 'asita', 'bharadwaja', 'brahma', 'brihadaswa', 'brihadratha', 'brihadyumna', 'chitrangada', 'dasaratha', 'dhanusaksha', 'dhaumya', 'dhrishtaketu', 'drupada', 'durvasa', 'ganapati', 'gandhari', 'ghalotkacha', 'hanuman',  'indrasena', 'iravan', 'janaka', 'janamejaya', 'jayatsena', 'kagola', 'kanika', 'kausikam', 'kartikeya', 'kekaya', 'ketama', 'kichaka', 'kripacharya', 'kritavarma', 'kunti', 'durvasa', 'madri', 'lakshmana', 'lomasa', 'lopamudra', 'mahendra', 'maitreya', 'mandavya', 'maricha', 'markandeya', 'marutta', 'kausika', 'brihaspati', 'matali', 'nahusha', 'nala', 'nandini', 'narada', 'pandu', 'parasara', 'paravasu', 'rukmini', 'prabhasa', 'pradyumna', 'pritha', 'purochana', 'purumitra', 'raibhya', 'sanatkumar', 'aditi', 'radheya', 'radha', 'romapada', 'rukma', 'sachidevi', 'saibya', 'samba', 'sanga', 'shanta', 'santanu', 'satyajit', 'satyaki', 'satyavati', 'sikhandin', 'somadutta', 'subahu', 'subhadra', 'sudeshna', 'sugriva', 'sujata', 'suka', 'supratika', 'susarma', 'rama', 'sveta', 'uddalaka', 'unchhavritti', 'urvasi', 'vaisampayana', 'yayati', 'mandhata', 'vali', 'vasishtha', 'ganga', 'vichitravirya', 'vikarna', 'vedavyasa', 'vichitravirya', 'vikarna', 'visoka', 'visvarupa', 'vritra', 'twashta', 'yama', 'yavakrida', 'yayati', 'sarmishtha', 'sukracharya', 'yudhamanyu', 'yuyudhana', 'yuyutsu', 'dhritarashtra', 'drona', 'anga', 'asmaka', 'bhagadatta', 'brihatbala', 'bhuminjaya', 'burisrwas', 'bibhatsu', 'chala', 'charachitra', 'chekitana', 'chitraksha', 'chitra', 'chitrayudha', 'devayani', 'chitravarma', 'chitrasena', 'durdhara', 'durjaya', 'durmarsha', 'durmata', 'durmukha', 'durvishaha', 'dushkarma', 'dussaha', 'jarasandha', 'jaya', 'jayadratha', 'karna', 'kartavirya', 'paurava', 'sakuni', 'salva', 'sisupala', 'sarasana', 'sarmishtha', 'satanika', 'satyavrata', 'sudakshina', 'sudarsana', 'suvarna', 'srutayu', 'astutayu', 'srutayudha', 'upachitra', 'vasudhana', 'vinda', 'anuvinda', 'vivimsati', 'vriddhakshatra', 'vrika', 'vrisha', 'achala', 'vrishnis', 'kekayas', 'vrishasena', 'alambasa', 'bakasura', 'hamsa', 'hidimbaka', 'kamsa', 'ilvala', 'indrajit', 'jalasura', 'kumbhakarna', 'ravana']
same_names_dict = {
                    'krishna': ['achuta', 'achyuta', 'bhagawan', 'govinda', 'hrishikesha', 'janardana', 'kesava', 'krishna', 'kurma', 'narayana', 'madhava', 'madhusudana', 'mahavishnu', 'vishnu', 'pundarikaksha', 'ptirushottama', 'purushottama', 'vasudeva', 'viswarupa', 'visvarupa', 'pandu'],
                    'yudhishthira': ['ajatasatru', 'dharmananda', 'kanka', 'yudhishthira'],
                    'arjuna' : ['arjuna', 'brihannola', 'dhananjaya', 'nara', 'partha', 'phalguna', 'savyasachin', 'jishnu', 'gudakesa', 'savyasachi'],
                    'bhima' : ['bhima' 'valala' 'vrikodara', 'bhimasena'],
                    'nakula' : ['nakula', 'dharmagranthi'],
                    'sahadeva' : ['sahadeva', 'tantripala'],
                    'bhishma' : ['bhishma', 'devavrata'],
                    'siva' : ['siva', 'rudra'],
                    'parvati' : ['parvati', 'umadevi'],
                    'vyasa' : ['krishna-dwaipayana', 'vyasa', 'vedavyasa'],
                    'balarama' : ['balarama', 'halayudha'],
                    'indra': [ 'indra', 'mahendra'],
                    'satyaki' : ['satyaki', 'yuyudhana'],
                    'draupadi' : ['draupadi', 'droupadi'],
                }


# names_dict = {
#                 "krishna": ["achuta", "achyuta", "bhagawan", "govinda", "hrishikesha", "janardana", "kesava", "krishna", "kurma", "narayana", "madhava", "madhusudana",
#                     "mahavishnu", "vishnu", "pundarikaksha", "ptirushottama", "purushottama","vasudeva", "viswarupa", "rama", "visvarupa"],
#                 "yudhishthira": ["ajatasatru", "dharmananda", "kanka", "yudhishthira"],
#                 "arjuna": ["arjuna", "brihannola", "dhananjaya", "nara", "partha", "phalguna", "savyasachin"],
#                 "bhima": ["bhima", "valala", "vrikodara"],
#                 "nakula": ["nakula", "dharmagranthi"],
#                 "sahadeva": ["sahadeva", "tantripala"],
#                 "bhishma": ["bhishma", "devavrata"],
#                 "siva": ["siva", "rudra"],
#                 "parvati": ["parvati", "umadevi"],
#                 "vyasa": ["krishna-dwaipayana", "vyasa", "vedavyasa"],
#                 "balarama": ["balarama", "halayudha"],
#                 "indra": ["indra", "mahendra"],
#                 "devaki": ["devaki"],
#                 "dhrishtadyumna": ["dhrishtadyumna"],
#                 "abhimanyu": ["abhimanyu"],
#                 "daruka": ["daruka"],
#                 "adhiratha": ["adhiratha"],
#                 "agastya": ["agastya"],
#                 "arundhati": ["arundhati"],
#                 "ashtavakra": ["ashtavakra"],
#                 "aswatthama": ["aswatthama"],
#                 "asita": ["asita"],
#                 "bharadwaja": ["bharadwaja"],
#                 "brahma": ["brahma"],
#                 "brihadaswa": ["brihadaswa"],
#                 "brihadratha": ["brihadratha"],
#                 "brihadyumna": ["brihadyumna"],
#                 "chitrangada": ["chitrangada"],
#                 "dasaratha": ["dasaratha"],
#                 "dhanusaksha": ["dhanusaksha"],
#                 "dhaumya": ["dhaumya"],
#                 "dhrishtaketu": ["dhrishtaketu"],
#                 "drupada": ["drupada"],
#                 "durvasa": ["durvasa"],
#                 "ganapati": ["ganapati"],
#                 "gandhari": ["gandhari"],
#                 "ghalotkacha": ["ghalotkacha"],
#                 "hanuman": ["hanuman"],
#                 "indrasena": ["indrasena"],
#                 "iravan": ["iravan"],
#                 "janaka": ["janaka"],
#                 "janamejaya": ["janamejaya"],
#                 "jayatsena": ["jayatsena"],
#                 "kagola": ["kagola"],
#                 "kanika": ["kanika"],
#                 "kausikam": ["kausikam"],
#                 "kartikeya": ["kartikeya"],
#                 "kekaya": ["kekaya"],
#                 "ketama": ["ketama"],
#                 "kichaka": ["kichaka"],
#                 "kripacharya": ["kripacharya"],
#                 "kritavarma": ["kritavarma"],
#                 "kunti": ["kunti"],
#                 "madri": ["madri"],
#                 "lakshmana": ["lakshmana"],
#                 "lomasa": ["lomasa"],
#                 "lopamudra": ["lopamudra"],
#                 "mahendra": ["mahendra"],
#                 "maitreya": ["maitreya"],
#                 "mandavya": ["mandavya"],
#                 "maricha": ["maricha"],
#                 "markandeya": ["markandeya"],
#                 "marutta": ["marutta"],
#                 "kausika": ["kausika"],
#                 "brihaspati": ["brihaspati"],
#                 "matali": ["matali"],
#                 "nahusha": ["nahusha"],
#                 "nala": ["nala"],
#                 "nandini": ["nandini"],
#                 "narada": ["narada"],
#                 "pandu": ["pandu"],
#                 "parasara": ["parasara"],
#                 "paravasu": ["paravasu"],
#                 "rukmini": ["rukmini"],
#                 "prabhasa": ["prabhasa"],
#                 "pradyumna": ["pradyumna"],
#                 "pritha": ["pritha"],
#                 "purochana": ["purochana"],
#                 "purumitra": ["purumitra"],
#                 "raibhya": ["raibhya"],
#                 "sanatkumar": ["sanatkumar"],
#                 "aditi": ["aditi"],
#                 "radheya": ["radheya"],
#                 "radha": ["radha"],
#                 "romapada": ["romapada"],
#                 "rukma": ["rukma"],
#                 "sachidevi": ["sachidevi"],
#                 "saibya": ["saibya"],
#                 "samba": ["samba"],
#                 "sanga": ["sanga"],
#                 "shanta": ["shanta"],
#                 "santanu": ["santanu"],
#                 "satyajit": ["satyajit"],
#                 "satyaki": ["satyaki"],
#                 "satyavati": ["satyavati"],
#                 "sikhandin": ["sikhandin"],
#                 "somadutta": ["somadutta"],
#                 "subahu": ["subahu"],
#                 "subhadra": ["subhadra"],
#                 "sudeshna": ["sudeshna"],
#                 "sugriva": ["sugriva"],
#                 "sujata": ["sujata"],
#                 "suka": ["suka"],
#                 "supratika": ["supratika"],
#                 "susarma": ["susarma"],
#                 "rama": ["rama"],
#                 "sveta": ["sveta"],
#                 "uddalaka": ["uddalaka"],
#                 "unchhavritti": ["unchhavritti"],
#                 "urvasi": ["urvasi"],
#                 "vaisampayana": ["vaisampayana"],
#                 "yayati": ["yayati"],
#                 "mandhata": ["mandhata"],
#                 "vali": ["vali"],
#                 "vasishtha": ["vasishtha"],
#                 "ganga": ["ganga"],
#                 "vikarna": ["vikarna"],
#                 "vedavyasa": ["vedavyasa"],
#                 "vichitravirya": ["vichitravirya"],
#                 "visoka": ["visoka"],
#                 "visvarupa": ["visvarupa"],
#                 "vritra": ["vritra"],
#                 "twashta": ["twashta"],
#                 "yama": ["yama"],
#                 "yavakrida": ["yavakrida"],
#                 "sarmishtha": ["sarmishtha"],
#                 "sukracharya": ["sukracharya"],
#                 "yudhamanyu": ["yudhamanyu"],
#                 "yuyudhana": ["yuyudhana"],
#                 "yuyutsu": ["yuyutsu"],
#                 "dhritarashtra": ["dhritarashtra"],
#                 "drona": ["drona"],
#                 "anga": ["anga"],
#                 "asmaka": ["asmaka"],
#                 "bhagadatta": ["bhagadatta"],
#                 "brihatbala": ["brihatbala"],
#                 "bhuminjaya": ["bhuminjaya"],
#                 "burisrwas": ["burisrwas"],
#                 "bibhatsu": ["bibhatsu"],
#                 "chala": ["chala"],
#                 "charachitra": ["charachitra"],
#                 "chekitana": ["chekitana"],
#                 "chitraksha": ["chitraksha"],
#                 "chitra": ["chitra"],
#                 "chitrayudha": ["chitrayudha"],
#                 "devayani": ["devayani"],
#                 "chitravarma": ["chitravarma"],
#                 "chitrasena": ["chitrasena"],
#                 "durdhara": ["durdhara"],
#                 "durjaya": ["durjaya"],
#                 "durmarsha": ["durmarsha"],
#                 "durmata": ["durmata"],
#                 "durmukha": ["durmukha"],
#                 "durvishaha": ["durvishaha"],
#                 "dushkarma": ["dushkarma"],
#                 "dussaha": ["dussaha"],
#                 "jarasandha": ["jarasandha"],
#                 "jaya": ["jaya"],
#                 "jayadratha": ["jayadratha"],
#                 "karna": ["karna"],
#                 "kartavirya": ["kartavirya"],
#                 "paurava": ["paurava"],
#                 "sakuni": ["sakuni"],
#                 "salva": ["salva"],
#                 "sisupala": ["sisupala"],
#                 "sarasana": ["sarasana"],
#                 "satanika": ["satanika"],
#                 "satyavrata": ["satyavrata"],
#                 "sudakshina": ["sudakshina"],
#                 "sudarsana": ["sudarsana"],
#                 "suvarna": ["suvarna"],
#                 "srutayu": ["srutayu"],
#                 "astutayu": ["astutayu"],
#                 "srutayudha": ["srutayudha"],
#                 "upachitra": ["upachitra"],
#                 "vasudhana": ["vasudhana"],
#                 "vinda": ["vinda"],
#                 "anuvinda": ["anuvinda"],
#                 "vivimsati": ["vivimsati"],
#                 "vriddhakshatra": ["vriddhakshatra"],
#                 "vrika": ["vrika"],
#                 "vrisha": ["vrisha"],
#                 "achala": ["achala"],
#                 "vrishnis": ["vrishnis"],
#                 "kekayas": ["kekayas"],
#                 "vrishasena": ["vrishasena"],
#                 "alambasa": ["alambasa"],
#                 "bakasura": ["bakasura"],
#                 "hamsa": ["hamsa"],
#                 "hidimbaka": ["hidimbaka"],
#                 "kamsa": ["kamsa"],
#                 "ilvala": ["ilvala"],
#                 "indrajit": ["indrajit"],
#                 "jalasura": ["jalasura"],
#                 "kumbhakarna": ["kumbhakarna"],
#                 "ravana": ["ravana"],
#             }
