project:
  type: website

website:
  title: "my_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yasaswi-p
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

input:
  - about.qmd
  - posts/post-with-code/index.qmd
  - posts/post-with-code/image.jpg
  - posts/post-with-code/test.ipynb